import { User, Product, InventoryMovement, QualityMetric, Supplier, Customer, Sale, AuditLog, Category } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    password: 'admin123',
    role: 'Administrador',
    fullName: 'Carlos Rodríguez',
    email: 'admin@pyme.com',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    username: 'empleado',
    password: 'emp123',
    role: 'Empleado',
    fullName: 'María González',
    email: 'maria@pyme.com',
    createdAt: new Date('2024-02-20'),
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electrónica',
    description: 'Dispositivos y equipos electrónicos',
    productCount: 2,
    createdAt: new Date('2023-11-01'),
  },
  {
    id: '2',
    name: 'Accesorios',
    description: 'Accesorios y periféricos',
    productCount: 3,
    createdAt: new Date('2023-11-01'),
  },
  {
    id: '3',
    name: 'Audio',
    description: 'Equipos de audio y sonido',
    productCount: 1,
    createdAt: new Date('2023-11-01'),
  },
  {
    id: '4',
    name: 'Almacenamiento',
    description: 'Dispositivos de almacenamiento',
    productCount: 1,
    createdAt: new Date('2023-11-01'),
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Tech Distributors SA',
    contactName: 'Roberto Martínez',
    phone: '+1-555-0101',
    email: 'contacto@techdist.com',
    address: 'Av. Tecnología 123, Ciudad',
    productsCount: 8,
    createdAt: new Date('2023-12-01'),
  },
  {
    id: '2',
    name: 'Gaming Gear Inc',
    contactName: 'Ana Silva',
    phone: '+1-555-0202',
    email: 'ventas@gaminggear.com',
    address: 'Calle Gamer 456, Ciudad',
    productsCount: 5,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'Display Solutions',
    contactName: 'Luis Fernández',
    phone: '+1-555-0303',
    email: 'info@displaysol.com',
    address: 'Boulevard Pantallas 789, Ciudad',
    productsCount: 3,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Audio Pro',
    contactName: 'Carmen Ruiz',
    phone: '+1-555-0404',
    email: 'contacto@audiopro.com',
    productsCount: 4,
    createdAt: new Date('2024-02-15'),
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'LAP-001',
    name: 'Laptop Dell Inspiron 15',
    description: 'Laptop para uso empresarial',
    category: 'Electrónica',
    categoryId: '1',
    currentStock: 15,
    minStock: 5,
    maxStock: 50,
    unitPrice: 850.00,
    supplierIds: ['1'],
    supplierNames: ['Tech Distributors SA'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: '2',
    sku: 'MOU-002',
    name: 'Mouse Inalámbrico Logitech',
    description: 'Mouse ergonómico inalámbrico',
    category: 'Accesorios',
    categoryId: '2',
    currentStock: 45,
    minStock: 20,
    maxStock: 100,
    unitPrice: 25.50,
    supplierIds: ['1'],
    supplierNames: ['Tech Distributors SA'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-11-02'),
  },
  {
    id: '3',
    sku: 'TEC-003',
    name: 'Teclado Mecánico RGB',
    description: 'Teclado mecánico para gaming',
    category: 'Accesorios',
    categoryId: '2',
    currentStock: 3,
    minStock: 10,
    maxStock: 40,
    unitPrice: 120.00,
    supplierIds: ['2'],
    supplierNames: ['Gaming Gear Inc'],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-11-03'),
  },
  {
    id: '4',
    sku: 'MON-004',
    name: 'Monitor LG 27" 4K',
    description: 'Monitor profesional 4K',
    category: 'Electrónica',
    categoryId: '1',
    currentStock: 8,
    minStock: 5,
    maxStock: 30,
    unitPrice: 450.00,
    supplierIds: ['3'],
    supplierNames: ['Display Solutions'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-10-28'),
  },
  {
    id: '5',
    sku: 'AUD-005',
    name: 'Audífonos Sony WH-1000XM4',
    description: 'Audífonos con cancelación de ruido',
    category: 'Audio',
    categoryId: '3',
    currentStock: 2,
    minStock: 8,
    maxStock: 25,
    unitPrice: 280.00,
    supplierIds: ['4'],
    supplierNames: ['Audio Pro'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-11-04'),
  },
  {
    id: '6',
    sku: 'WEB-006',
    name: 'Webcam Logitech C920',
    description: 'Webcam Full HD 1080p',
    category: 'Accesorios',
    categoryId: '2',
    currentStock: 22,
    minStock: 10,
    maxStock: 50,
    unitPrice: 95.00,
    supplierIds: ['1'],
    supplierNames: ['Tech Distributors SA'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-10-30'),
  },
  {
    id: '7',
    sku: 'SSD-007',
    name: 'SSD Samsung 1TB',
    description: 'Disco sólido interno 1TB',
    category: 'Almacenamiento',
    categoryId: '4',
    currentStock: 18,
    minStock: 8,
    maxStock: 40,
    unitPrice: 180.00,
    supplierIds: ['1'],
    supplierNames: ['Tech Distributors SA'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-11-01'),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Empresa XYZ',
    contactName: 'Pedro Sánchez',
    phone: '+1-555-1001',
    email: 'pedro@empresaxyz.com',
    address: 'Av. Principal 100, Ciudad',
    status: 'activo',
    totalPurchases: 12450.50,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'TechCorp Solutions',
    contactName: 'Laura Díaz',
    phone: '+1-555-1002',
    email: 'laura@techcorp.com',
    address: 'Calle Comercio 250, Ciudad',
    status: 'activo',
    totalPurchases: 8920.00,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'Oficinas Modernas SA',
    contactName: 'Jorge López',
    phone: '+1-555-1003',
    email: 'jorge@oficinamodernas.com',
    address: 'Calle Industrial 75, Ciudad',
    status: 'activo',
    totalPurchases: 15600.75,
    createdAt: new Date('2024-03-05'),
  },
];

export const mockMovements: InventoryMovement[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Laptop Dell Inspiron 15',
    sku: 'LAP-001',
    type: 'entrada',
    quantity: 10,
    reason: 'Compra a proveedor',
    performedBy: 'Carlos Rodríguez',
    date: new Date('2024-11-01'),
    notes: 'Pedido mensual',
  },
  {
    id: '2',
    productId: '2',
    productName: 'Mouse Inalámbrico Logitech',
    sku: 'MOU-002',
    type: 'salida',
    quantity: 15,
    reason: 'Venta a cliente',
    performedBy: 'María González',
    date: new Date('2024-11-02'),
    notes: 'Cliente: Empresa XYZ',
    customerId: '1',
    customerName: 'Empresa XYZ',
  },
  {
    id: '3',
    productId: '3',
    productName: 'Teclado Mecánico RGB',
    sku: 'TEC-003',
    type: 'salida',
    quantity: 7,
    reason: 'Venta a cliente',
    performedBy: 'María González',
    date: new Date('2024-11-03'),
    customerId: '2',
    customerName: 'TechCorp Solutions',
  },
  {
    id: '4',
    productId: '4',
    productName: 'Monitor LG 27" 4K',
    sku: 'MON-004',
    type: 'entrada',
    quantity: 5,
    reason: 'Reposición de stock',
    performedBy: 'Carlos Rodríguez',
    date: new Date('2024-11-04'),
  },
  {
    id: '5',
    productId: '1',
    productName: 'Laptop Dell Inspiron 15',
    sku: 'LAP-001',
    type: 'salida',
    quantity: 3,
    reason: 'Venta a cliente',
    performedBy: 'María González',
    date: new Date('2024-10-28'),
    customerId: '3',
    customerName: 'Oficinas Modernas SA',
  },
  {
    id: '6',
    productId: '6',
    productName: 'Webcam Logitech C920',
    sku: 'WEB-006',
    type: 'entrada',
    quantity: 20,
    reason: 'Compra a proveedor',
    performedBy: 'Carlos Rodríguez',
    date: new Date('2024-10-25'),
  },
];

export const mockSales: Sale[] = [
  {
    id: '1',
    customerId: '1',
    customerName: 'Empresa XYZ',
    items: [
      {
        productId: '2',
        productName: 'Mouse Inalámbrico Logitech',
        sku: 'MOU-002',
        quantity: 15,
        unitPrice: 25.50,
        subtotal: 382.50,
      },
    ],
    total: 382.50,
    date: new Date('2024-11-02'),
    performedBy: 'María González',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'TechCorp Solutions',
    items: [
      {
        productId: '3',
        productName: 'Teclado Mecánico RGB',
        sku: 'TEC-003',
        quantity: 7,
        unitPrice: 120.00,
        subtotal: 840.00,
      },
    ],
    total: 840.00,
    date: new Date('2024-11-03'),
    performedBy: 'María González',
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'Oficinas Modernas SA',
    items: [
      {
        productId: '1',
        productName: 'Laptop Dell Inspiron 15',
        sku: 'LAP-001',
        quantity: 3,
        unitPrice: 850.00,
        subtotal: 2550.00,
      },
    ],
    total: 2550.00,
    date: new Date('2024-10-28'),
    performedBy: 'María González',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Carlos Rodríguez',
    action: 'create',
    entity: 'product',
    entityId: '1',
    entityName: 'Laptop Dell Inspiron 15',
    details: 'Creó el producto Laptop Dell Inspiron 15 (SKU: LAP-001)',
    timestamp: new Date('2024-01-10T10:30:00'),
  },
  {
    id: '2',
    userId: '1',
    userName: 'Carlos Rodríguez',
    action: 'movement',
    entity: 'inventory',
    entityId: '1',
    entityName: 'Entrada: Laptop Dell Inspiron 15',
    details: 'Registró entrada de 10 unidades - Compra a proveedor',
    timestamp: new Date('2024-11-01T14:20:00'),
  },
  {
    id: '3',
    userId: '2',
    userName: 'María González',
    action: 'sale',
    entity: 'inventory',
    entityId: '2',
    entityName: 'Venta: Mouse Inalámbrico Logitech',
    details: 'Venta de 15 unidades a Empresa XYZ por $382.50',
    timestamp: new Date('2024-11-02T11:15:00'),
  },
  {
    id: '4',
    userId: '2',
    userName: 'María González',
    action: 'sale',
    entity: 'inventory',
    entityId: '3',
    entityName: 'Venta: Teclado Mecánico RGB',
    details: 'Venta de 7 unidades a TechCorp Solutions por $840.00',
    timestamp: new Date('2024-11-03T09:45:00'),
  },
  {
    id: '5',
    userId: '1',
    userName: 'Carlos Rodríguez',
    action: 'edit',
    entity: 'product',
    entityId: '4',
    entityName: 'Monitor LG 27" 4K',
    details: 'Actualizó el precio unitario de $420.00 a $450.00',
    timestamp: new Date('2024-10-28T16:30:00'),
  },
  {
    id: '6',
    userId: '1',
    userName: 'Carlos Rodríguez',
    action: 'create',
    entity: 'supplier',
    entityId: '1',
    entityName: 'Tech Distributors SA',
    details: 'Creó el proveedor Tech Distributors SA',
    timestamp: new Date('2023-12-01T08:00:00'),
  },
  {
    id: '7',
    userId: '1',
    userName: 'Carlos Rodríguez',
    action: 'create',
    entity: 'customer',
    entityId: '1',
    entityName: 'Empresa XYZ',
    details: 'Creó el cliente Empresa XYZ',
    timestamp: new Date('2024-01-20T10:00:00'),
  },
];

export const mockQualityMetrics: QualityMetric[] = [
  {
    category: 'Rendimiento',
    metric: 'Tiempo de carga promedio',
    value: 1.2,
    target: 2.0,
    unit: 'seg',
    status: 'excellent',
  },
  {
    category: 'Rendimiento',
    metric: 'Tiempo de respuesta',
    value: 0.8,
    target: 1.0,
    unit: 'seg',
    status: 'excellent',
  },
  {
    category: 'Rendimiento',
    metric: 'Transacciones por segundo',
    value: 450,
    target: 500,
    unit: 'TPS',
    status: 'good',
  },
  {
    category: 'Fiabilidad',
    metric: 'Disponibilidad del sistema',
    value: 99.8,
    target: 99.5,
    unit: '%',
    status: 'excellent',
  },
  {
    category: 'Fiabilidad',
    metric: 'Tasa de errores',
    value: 0.05,
    target: 0.1,
    unit: '%',
    status: 'excellent',
  },
  {
    category: 'Fiabilidad',
    metric: 'Tiempo medio entre fallos',
    value: 720,
    target: 500,
    unit: 'horas',
    status: 'excellent',
  },
  {
    category: 'Usabilidad',
    metric: 'Satisfacción del usuario',
    value: 4.6,
    target: 4.0,
    unit: '/5',
    status: 'excellent',
  },
  {
    category: 'Usabilidad',
    metric: 'Tasa de éxito de tareas',
    value: 94,
    target: 90,
    unit: '%',
    status: 'excellent',
  },
  {
    category: 'Usabilidad',
    metric: 'Tiempo promedio de tarea',
    value: 45,
    target: 60,
    unit: 'seg',
    status: 'excellent',
  },
];
